# Generated by Django 4.1.7 on 2023-03-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_failedpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='method',
            field=models.CharField(default=' ', max_length=40),
        ),
    ]
