# Generated by Django 4.1.7 on 2023-03-01 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_alter_course_title_img'),
        ('purchase', '0004_paymentinfo_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='course',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
