# Generated by Django 4.1.7 on 2023-02-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title_img',
            field=models.ImageField(default='hacker.png', upload_to=''),
        ),
    ]
