# Generated by Django 4.1.7 on 2023-03-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_meet_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='meet_link',
        ),
    ]
