# Generated by Django 4.1.7 on 2023-03-05 15:29

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='profile',
            field=models.ImageField(default='defualt.jpeg', upload_to=user.models.imgFolder),
        ),
    ]
