# Generated by Django 4.1.7 on 2023-03-08 13:08

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_extenduser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='profile',
            field=models.ImageField(default='img/hacker.png', upload_to=user.models.imgFolder),
        ),
    ]
